import {
  siPython,
  siFastapi,
  siFlask,
  siReact,
  siNextdotjs,
  siTypescript,
  siTailwindcss,
  siShadcnui,
  siFramer,
  siDocker,
  siLinux,
  siGit,
  siGithub,
  siGithubactions,
  siNginx,
  siVercel,
  siHuggingface,
  siVscodium,
  siPycharm,
  siPostman,
  siFigma,
  siNpm,
  siPnpm,
} from "simple-icons";
import type { TechCategory } from "./types";

export const techCategories: TechCategory[] = [
  {
    id: "backend",
    title: "Backend",
    description: "Servers, APIs, and the logic that powers applications.",
    categoryIcon: "⚙️",
    items: [
      { name: "Python", iconPath: siPython.path, iconColor: `#${siPython.hex}`, description: "Primary language for automation, backend APIs, AI experiments, and scripting.", featured: true },
      { name: "FastAPI", iconPath: siFastapi.path, iconColor: `#${siFastapi.hex}`, description: "Preferred framework for building scalable, async REST APIs.", featured: true },
      { name: "Flask", iconPath: siFlask.path, iconColor: `#${siFlask.hex}`, description: "Lightweight Python web framework for smaller services and prototyping." },
      { name: "REST APIs", iconPath: siPostman.path, iconColor: `#${siPostman.hex}`, description: "Designing and consuming RESTful API architectures." },
      { name: "WebSockets", iconPath: siNginx.path, iconColor: `#${siNginx.hex}`, description: "Real-time bidirectional communication for live features." },
    ],
  },
  {
    id: "frontend",
    title: "Frontend",
    description: "Interfaces that are fast, accessible, and delightful.",
    categoryIcon: "🖥️",
    items: [
      { name: "React", iconPath: siReact.path, iconColor: `#${siReact.hex}`, description: "Building component-driven UIs with hooks and modern patterns." },
      { name: "Next.js", iconPath: siNextdotjs.path, iconColor: `#${siNextdotjs.hex}`, description: "Full-stack React framework used for this portfolio." },
      { name: "TypeScript", iconPath: siTypescript.path, iconColor: `#${siTypescript.hex}`, description: "Type-safe JavaScript for scalable applications." },
      { name: "Tailwind CSS", iconPath: siTailwindcss.path, iconColor: `#${siTailwindcss.hex}`, description: "Utility-first CSS framework for rapid, consistent styling." },
      { name: "shadcn/ui", iconPath: siShadcnui.path, iconColor: `#${siShadcnui.hex}`, description: "Accessible component library built on Radix UI and Tailwind." },
      { name: "Framer Motion", iconPath: siFramer.path, iconColor: `#${siFramer.hex}`, description: "Production-ready animation library for React." },
    ],
  },
  {
    id: "devops",
    title: "DevOps",
    description: "Shipping reliably from code to production.",
    categoryIcon: "🚀",
    items: [
      { name: "Docker", iconPath: siDocker.path, iconColor: `#${siDocker.hex}`, description: "Containerization and deployment across projects.", featured: true },
      { name: "Linux", iconPath: siLinux.path, iconColor: `#${siLinux.hex}`, description: "Daily driver OS for server administration and scripting.", featured: true },
      { name: "Git", iconPath: siGit.path, iconColor: `#${siGit.hex}`, description: "Version control, branching, and collaborative workflows." },
      { name: "GitHub", iconPath: siGithub.path, iconColor: `#${siGithub.hex}`, description: "Repository hosting, pull requests, and project management." },
      { name: "GitHub Actions", iconPath: siGithubactions.path, iconColor: `#${siGithubactions.hex}`, description: "CI/CD pipelines for automated testing and deployment." },
      { name: "Nginx", iconPath: siNginx.path, iconColor: `#${siNginx.hex}`, description: "Reverse proxy and web server configuration." },
      { name: "Vercel", iconPath: siVercel.path, iconColor: `#${siVercel.hex}`, description: "Serverless deployment platform for Next.js projects." },
    ],
  },
  {
    id: "ai",
    title: "Artificial Intelligence",
    description: "Exploring the frontier where software meets intelligence.",
    categoryIcon: "🤖",
    items: [
      { name: "OpenAI API", iconPath: siHuggingface.path, iconColor: "#10a37f", description: "Integrating GPT models for automation and AI features." },
      { name: "Hugging Face", iconPath: siHuggingface.path, iconColor: `#${siHuggingface.hex}`, description: "Using open-source models for NLP and ML experiments." },
      { name: "Transformers", iconPath: siHuggingface.path, iconColor: `#${siHuggingface.hex}`, description: "Learning the architecture behind modern large language models." },
      { name: "Prompt Engineering", iconPath: siHuggingface.path, iconColor: `#${siHuggingface.hex}`, description: "Crafting effective prompts for reliable model outputs." },
    ],
  },
  {
    id: "tools",
    title: "Development Tools",
    description: "The tools that make the workflow smooth.",
    categoryIcon: "🛠️",
    items: [
      { name: "VS Code", iconPath: siVscodium.path, iconColor: `#${siVscodium.hex}`, description: "Primary code editor with a customized setup." },
      { name: "PyCharm", iconPath: siPycharm.path, iconColor: `#${siPycharm.hex}`, description: "Used for complex Python projects with debugging." },
      { name: "Postman", iconPath: siPostman.path, iconColor: `#${siPostman.hex}`, description: "API testing, documentation, and collection management." },
      { name: "Figma", iconPath: siFigma.path, iconColor: `#${siFigma.hex}`, description: "UI design and prototyping for interface planning." },
      { name: "npm", iconPath: siNpm.path, iconColor: `#${siNpm.hex}`, description: "Package management for JavaScript and Node.js." },
      { name: "pnpm", iconPath: siPnpm.path, iconColor: `#${siPnpm.hex}`, description: "Fast, disk-efficient package manager." },
    ],
  },
];
